name: Pimmi Pande
favicon: null
layout_spectrum: 0.9548617957625538
typography_spectrum: 0.2078509966377169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080403'
    - '#3d302a'
    - '#c15324'
    - '#56caa9'
    - '#eac68c'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.976817738963291
  rhythmicContrast: 0.2410452978219837
purpose: []
